# Generated by Django 4.2.1 on 2023-06-04 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='categoria',
            name='sigla',
            field=models.CharField(default='aaa', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.marca'),
        ),
    ]
