# Generated by Django 4.2.1 on 2023-06-04 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_marca_nombre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Producto',
        ),
    ]
